name: "Unit test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    uses: ./.github/workflows/setup-environment.yml
    runs-on: ubuntu-20.04
    steps:
      - name: Run PHPUnit
        run: composer phpunit
